# Lists

In [ ]:
# Creating a list
my_list = [1, 'hello', 3.14, [2, 4]]

In [ ]:
# type([])
# type(my_list)

list

In [ ]:
# Accessing and modifying
print(my_list[1])   # Output: 'hello'
my_list[0] = 100    # Updates first element to 100

# Arrays

In [6]:
# ! pip install numpy
import numpy as np

In [ ]:

# Creating a NumPy array
np_array = np.array([1, 2, 3, 4])

# Arithmetic operations (element-wise)
print(np_array + 10)  # Output: [11 12 13 14]

# Multidimensional arrays
matrix = np.array([[1, 2], [3, 4]])
print(matrix[1, 1])  # Output: 4


# List Comprehension in Python

In [ ]:
[expression for item in iterable if condition]

In [ ]:
# Squares of numbers from 1 to 5
squares = [x**2 for x in range(1, 6)]
print(squares)  # Output: [1, 4, 9, 16, 25]

In [ ]:
# Even numbers from 1 to 10
evens = [x for x in range(1, 11) if x % 2 == 0]
print(evens)  # Output: [2, 4, 6, 8, 10]

In [ ]:
# Flattening a 2D list
matrix = [[1, 2], [3, 4], [5, 6]]
flat = [num for row in matrix for num in row]
print(flat)  # Output: [1, 2, 3, 4, 5, 6]

In [ ]:
# Creating arrays
array1 = np.array([1, 2, 3, 4])  # 1D array
array2 = np.array([[1, 2], [3, 4]])  # 2D array

print(array1)  # Output: [1 2 3 4]
print(array2)
# Output:
# [[1 2]
#  [3 4]]

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
print(a + b)  # Output: [5 7 9]

# Multiplication
print(a * b)  # Output: [4 10 18]

# Scalar multiplication
print(a * 2)  # Output: [2 4 6]

In [ ]:
data = np.array([1, 2, 3, 4, 5])

# Mean
print(np.mean(data))  # Output: 3.0

# Sum
print(np.sum(data))  # Output: 15

# Standard deviation
print(np.std(data))  # Output: 1.4142135623730951

In [ ]:
# Slicing
array = np.array([10, 20, 30, 40, 50])
print(array[1:4])  # Output: [20 30 40]

# Multidimensional indexing
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix[1, 1])  # Output: 4  (second row, second column)
print(matrix[:, 0])  # Output: [1 3 5] (first column)

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])

# Add b to each row of a
print(a + b)
# Output:
# [[11 22]
#  [13 24]]

In [ ]:
# Reshape
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Transpose
matrix = np.array([[1, 2], [3, 4]])
print(matrix.T)
# Output:
# [[1 3]
#  [2 4]]

In [ ]:
# List of known malicious IPs
malicious_ips = ['192.168.1.1', '10.0.0.1', '203.0.113.5']

# Example incoming connection logs
connection_logs = [
    '192.168.1.1',
    '172.16.0.2',
    '203.0.113.5',
    '8.8.8.8'
]

# Check if any IP in the logs is malicious
detected_ips = [ip for ip in connection_logs if ip in malicious_ips]
print("Detected Malicious IPs:", detected_ips)
# Output: Detected Malicious IPs: ['192.168.1.1', '203.0.113.5']

In [ ]:
import numpy as np

# Example packet sizes (in bytes) from network traffic
packet_sizes = np.array([150, 200, 180, 170, 10000, 160, 190])

# Calculate statistics
mean_size = np.mean(packet_sizes)
std_dev = np.std(packet_sizes)

# Flag packets that deviate significantly from the mean
anomalies = packet_sizes[np.abs(packet_sizes - mean_size) > 3 * std_dev]
print("Anomalous Packet Sizes:", anomalies)
# Output: Anomalous Packet Sizes: [10000]

In [ ]:
# Example text data
text = "Artificial Intelligence is transforming cybersecurity."

# Tokenize text into words
tokens = [word.lower() for word in text.split()]
print("Tokens:", tokens)
# Output: Tokens: ['artificial', 'intelligence', 'is', 'transforming', 'cybersecurity']

In [ ]:
# Input layer (features)
inputs = np.array([0.5, 1.5])

# Weights for a hidden layer
weights = np.array([[0.2, 0.8], [0.5, 0.1]])

# Biases
biases = np.array([0.1, 0.2])

# Compute hidden layer outputs: (inputs * weights) + biases
outputs = np.dot(inputs, weights) + biases
print("Hidden Layer Outputs:", outputs)
# Output: Hidden Layer Outputs: [0.85 0.95]